services:
  app:
    build: .
    image: shipping-app
    restart: on-failure
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    container_name: shipping-app
    volumes:
      - .:/shipping-software
    ports:
      - "${SERVER_PORT}:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    environment:
        - HOST=${HOST}
        - DEVELOPMENT_DATABASE_USERNAME=${DEVELOPMENT_DATABASE_USERNAME}
        - DEVELOPMENT_DATABASE_PASSWORD=${DEVELOPMENT_DATABASE_PASSWORD}
        - PRODUCTION_DATABASE_USERNAME=${PRODUCTION_DATABASE_USERNAME}
        - PRODUCTION_DATABASE_PASSWORD=${PRODUCTION_DATABASE_PASSWORD}
        - RAILS_ENV=${RAILS_ENV}
        - PRODUCTION_DATABASE_HOST=${PRODUCTION_DATABASE_HOST}
  background:
    image: shipping-app
    container_name: shipping-background
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/shipping-software
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - app
    environment:
        - HOST=${HOST}
        - DEVELOPMENT_DATABASE_USERNAME=${DEVELOPMENT_DATABASE_USERNAME}
        - DEVELOPMENT_DATABASE_PASSWORD=${DEVELOPMENT_DATABASE_PASSWORD}
        - PRODUCTION_DATABASE_USERNAME=${PRODUCTION_DATABASE_USERNAME}
        - PRODUCTION_DATABASE_PASSWORD=${PRODUCTION_DATABASE_PASSWORD}
        - RAILS_ENV=${RAILS_ENV}
        - PRODUCTION_DATABASE_HOST=${PRODUCTION_DATABASE_HOST}
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    volumes:
      - D:\Documents\sql\shipping\data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - DEVELOPMENT_DATABASE_USERNAME=${DEVELOPMENT_DATABASE_USERNAME}
        - DEVELOPMENT_DATABASE_PASSWORD=${DEVELOPMENT_DATABASE_PASSWORD}
        - PRODUCTION_DATABASE_USERNAME=${PRODUCTION_DATABASE_USERNAME}
        - PRODUCTION_DATABASE_PASSWORD=${PRODUCTION_DATABASE_PASSWORD}
  redis:
    image: redis:7.2.3
    restart: always
    volumes:
      - D:\Documents\shipping_redis\:/data
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   ports:
  #     - "5100:80"
  #   volumes:
  #     - D:\Documents\pgadmin4\servers:/pgadmin4/servers
  #     - D:\Documents\pgadmin4\preferences:/pgadmin4/preferences

  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=abcd1234
  #     - PGADMIN_DEFAULT_EMAIL=admin@allegra.dept.store.com
volumes:
  pgdata: