#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DEVELOPMENT_DATABASE_USERNAME with encrypted password '$DEVELOPMENT_DATABASE_PASSWORD';
  CREATE USER $PRODUCTION_DATABASE_USERNAME with encrypted password '$PRODUCTION_DATABASE_PASSWORD';
	CREATE DATABASE shipping_software_development WITH OWNER $DEVELOPMENT_DATABASE_USERNAME;
  CREATE DATABASE shipping_software_production WITH OWNER $PRODUCTION_DATABASE_USERNAME;
	GRANT ALL PRIVILEGES ON DATABASE "shipping_software_development" TO "$DEVELOPMENT_DATABASE_USERNAME";
	GRANT ALL PRIVILEGES ON DATABASE "shipping_software_production" TO "$PRODUCTION_DATABASE_USERNAME";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "shipping_software_development" <<-EOSQL
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DEVELOPMENT_DATABASE_USERNAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "shipping_software_production" <<-EOSQL
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $PRODUCTION_DATABASE_USERNAME;
EOSQL