ports = [
  ['Tanjung Priok', 'Jakarta'],
  ['Merak', 'Banten'],
  ['Bakauheni', 'Lampung'],
  ['Tanjung Mas', 'Semarang'],
  ['Tanjung Intan', 'Cilacap'],
  ['Guluk', 'Sumenep'],
  ['Kalianget', 'Surabaya'],
  ['Kalimas', 'Surabaya'],
  ['Kamal', 'Bangkalan'],
  ['Ketapang', 'Banyuwangi'],
  ['Tanjung Perak', 'Surabaya'],
  ['Ujung', 'Surabaya'],
  ['Tanjung Wangi', 'Kalipuro'],
  ['Cirebon', 'Jawa Barat'],
  ['Pertiwi', 'Subang'],
  ['Pramuka', 'Garut'],
  ['Sunda Kelapa', 'Jakarta'],
  ['ASDP Jagoh', 'Kepulauan Riau'],
  ['ASDP Dompak', 'Tanjungpinang'],
  ['Bakong', 'Kepulauan Riau'],
  ['Batam Center', 'Pulau Batam'],
  ['Kote', 'Kepulauan Riau'],
  ['Harbour Bay', 'Batam'],
  ['Marok Tua', 'Kepulauan Riau'],
  ['Telaga Punggur', 'Batam'],
  ['Tarempa', 'Kepulauan Riau'],
  ['Teluk Bayur', 'Padang'],
  ['Muara', 'Padang'],
  ['Tanjung Pandan', 'Kabupaten Belitung'],
  ['Tanjung Balai', 'Medan'],
  ['Belawan', 'Medan'],
  ['Yoseph Iskandar', 'Padang'],
  ['Krueng Geukueh', 'Aceh'],
  ['Soekarno-Hatta', 'Makassar'],
  ['Gorontalo dan Anggrek', 'Gorontalo'],
  ['Paotere', 'Sulawesi Selatan'],
  ['Pamatata', 'Sulawesi Selatan'],
  ['Tanjung Ringgit', 'Sulawesi Selatan'],
  ['Bitung', 'Sulawesi Utara'],
  ['Donggala', 'Sulawesi Tengah'],
  ['Belopa', 'Sulawesi Selatan'],
  ['Malili', 'Sulawesi Selatan'],
  ['Pare Pare', 'Sulawesi Selatan'],
  ['Barru', 'Sulawesi Selatan'],
  ['Kendari', 'Sulawesi Tenggara'],
  ['Buton', 'Sulawesi Tenggara'],
  ['Banjarmasin', 'Kalimantan Selatan'],
  ['Dwikora', 'Pontianak'],
  ['Palangkaraya', 'Kalimantan Tengah'],
  ['Semayang', 'Kalimantan Timur'],
  ['Malundung', 'Tarakan'],
  ['Trisakti', 'Banjarmasin'],
  ['Samudera', 'Kalimantan Timur'],
  ['Gilimanuk', 'Bali'],
  ['Labuan Bajo', 'Lombok'],
  ['Rinca', 'NTT'],
  ['Dermaga Pink', 'NTT'],
  ['Pulau Molas', 'Flores'],
  ['Aimere', 'NTT'],
  ['Pota', 'Kabupaten Manggarai'],
  ['Mamboro', 'NTT'],
  ['Waingapu', 'Sumba Timur'],
  ['Tobelo', 'Maluku Utara'],
  ['Galela', 'Maluku Utara'],
  ['Wonreli', 'Maluku Barat Daya'],
  ['Pulau Teor', 'Kabupaten Seram'],
  ['Tutu Kembong', 'Maluku Tenggara'],
  ['Merauke', 'Papua'],
  ['Nabire', 'Papua'],
  ['Biak', 'Papua'],
  ['Omako', 'Papua'],
  ['Jayapura', 'Papua Barat'],
  ['Fak-fak', 'Papua Barat'],
  ['Kaimana', 'Papua Barat'],
  ['Bintuni', 'Papua Barat'],
]
ports.each do |(name,city)|
  Port.find_or_create_by(name: name,city: city, country: 'indonesia')
end
